---
title: "01_sample_data"
author: "Jae Yeon Kim"
date: "6/29/2020"
output: html_document
---

# Import libs and files 

## Libs

```{r}

pacman::p_load(jsonlite, # for importing json data 
               tidyverse, # for tidyverse 
               here, # for reproducibility
               tidyjson, # for json data manipulation 
               purrr) # for functional programming 

```

## Files 

```{r}

listed <- read_json(here("processed_data", "sampled.jsonl"))

```

# Turn a JSON file into a dataframe 

```{r}

# Gather keys 
keys <- listed %>% gather_keys()

# Identify unique keys 
unique(keys$key)

```

```{r}

# Putting together interested keys and values as a data frame 
df <- listed %>% spread_values(
    id = jnumber("id"),
    text = jstring("full_text"),
    retweet_count = jnumber("retweet_count"),
    favorite_count = jnumber("favorite_count"),
    user = jstring("user"),
    countries = jstring("withheld_in_countries")
)

```

# Export dataframe 

```{r}

write_rds(df, here("processed_data", "df.rds"))
```


