---
title: "03_preprocess_data"
author: "Jae Yeon Kim"
date: "7/2/2020"
output: html_document
---

# Import packages and files 

## Packages

```{r}

pacman::p_load(tidyverse, # for tidyverse 
               ggpubr, # for arranging ggplots   
               ggthemes, # for fancy ggplot themes
               here, # for reproducibility 
               countrycode, # to convert country code <-> country name 
               stringr, # for easy regular expression
               lubridate, # for easy time var manipulation
               forcats) # reverse factor order 

# for publication-friendly theme 
theme_set(theme_pubr())

```

## Files 

```{r}

parsed <- readRDS(file.choose())

```

## Wrangle 

### Select and Filter 

```{r}

# Select columns 
selected <- parsed %>% 
    select(country_code, created_at, full_text) %>%
    filter(!is.na(country_code))

# Remove cases where country code is ""
selected <- selected %>%
    filter(!(country_code == ""))
```

### Mutate 

```{r}

# Lower case 
selected$full_text <- str_to_lower(selected$full_text)

# Create new columns 
selected <- selected %>%
    mutate(full_text = str_to_lower(full_text),
           wuhan = as.numeric(str_detect(full_text, "wuhan")),
           asian = as.numeric(str_detect(full_text, "asia|asian")),
           chinese = as.numeric(str_detect(full_text, "china|chinese")),
           non_asian = as.numeric(!str_detect(full_text, "wuhan|asia|asian|china|chinese")), 
           US = ifelse(country_code == "US", 1, 0),
           country_name = countrycode(country_code, "iso2c", "country.name")
    )

# Reformat date-time 
selected$date <- as.POSIXct(selected$created_at, 
                            tz = "UTC",
                            format = "%a %b %d %H:%M:%S %z %Y") %>% #
                 word(1) # Only year month date 

# Only month 
# selected$month <- months(as.Date(selected$date)) %>%
#    fct_relevel("January", "February", "March", "April", "May", # "June") # Relevel factor order 

# Remove except selected
# rm(list = setdiff(ls(), "selected"))

```

## Explore 

- Trends in the top 10 countries (by count)

```{r}

# Create a list 
sorted <- selected %>% 
    group_by(country_name) %>%
    count(sort = TRUE) 

# Subquery, group by, then visualize 
selected %>%
    filter(country_name == intersect(country_name, sorted$country_name[1:9])) %>%
    group_by(country_name, date) %>%
    count() %>%
    ggplot(aes(x = as.Date(date), y = n, group = 1)) +
        geom_line() +
        facet_wrap(~country_name, ncol = 3) +
        labs(x = "Date",
             y = "Count",
             title = "The Count of Tweets on COVID-19",
             subtitle = "These nine countries were selected by the number of tweets.")

ggsave(here("outputs", "top9_countries.png"), height = 7)

```

- Trends in the US and UK (with a focus on concerned categories)

```{r}
selected %>%
    filter(country_name %in% c("United States", "United Kingdom")) %>%
    group_by(country_name, date, categories) %>%
    count() %>%
    ggplot(aes(x = as.Date(date), y = n, group = 1,
               col = factor(categories))) +
        geom_line() +
        facet_grid(~country_name) +
        labs(x = "Date",
             y = "Count",
             title = "The Count of Tweets on COVID-19 in Top 10 Countries")

```


- 


