---
title: "03_preprocess_data"
author: "Jae Yeon Kim"
date: "7/2/2020"
output: html_document
---

# Import packages and files 

## Packages

```{r}

pacman::p_load(tidyverse, # for tidyverse 
               ggpubr, # for arranging ggplots   
               ggthemes, # for fancy ggplot themes
               here, # for reproducibility 
               countrycode, # to convert country code <-> country name 
               stringr, # for easy regular expression
               lubridate, # for easy time var manipulation
               forcats, # reverse factor order 
               patchwork, # for easy ggarrange
               ggsci, # for pubs 
               caret, # for ML in R
               textclean, # to clean text 
               fastDummies, # to create dummy variables fast
               keyATM) # for keyword based topic modeling 

# for publication-friendly theme 
theme_set(theme_pubr())

# custom functions
source(here("functions", "stacked_bar_plot.R"))

```

## Files 

```{r}

df <- read_csv(here("processed_data", "text_ready.csv"))

```

## Add covariates 

```{r}
# Trump
df <- df %>%
    mutate(wuhan = as.numeric(str_detect(full_text, "trump")))

# Hashtags 
df <- df %>%
    mutate(hashtags = str_extract_all(full_text, "#\\S+")) %>% # extract hashtags 
    unnest() %>%
    mutate(hashtags = str_replace_all(hashtags, "[[:punct:]]", "")) %>% # replace all special characters 
    mutate(hashtags = str_replace_all(hashtags, "\\ー", ""))

```

```{r}

# Sort the count of hashtags 
sorted <- df %>% 
    group_by(hashtags) %>%
    count(sort = TRUE) 

# Create a new var for top 300 hashtags 
df$top_hashtags <- ifelse(df$hashtags %in% setdiff(sorted$hashtags, c(colnames(df), "asia", "china", "trump"))[1:300], df$hashtags, "others")

# Turn top hashtags into dummy variables 
#df <- dummy_cols(df, select_columns = "top_hashtags")

#colnames(df) <- str_replace_all(colnames(df), "top_hashtags_", "")
```

# Preprocess 

# Topic modeling 

